# Generated by CMake

if ("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif ()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.17)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach (_expectedTarget scala_decoder::scala_decoder_sdk)
  list(APPEND _expectedTargets ${_expectedTarget})
  if (NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif ()
  if (TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif ()
endforeach ()

unset(_targetsNotDefined)
if ("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif ()
if (NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\n"
                      "Targets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif ()
unset(_targetsDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if (_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif ()

# Create imported target scala_decoder::scala_decoder_sdk
add_library(scala_decoder::scala_decoder_sdk STATIC IMPORTED)

set_target_properties(scala_decoder::scala_decoder_sdk PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include"
        CXX_STANDARD 11
        CXX_STANDARD_REQUIRED YES
        CXX_EXTENSIONS NO
  )

if (CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif ()

set_property(TARGET scala_decoder::scala_decoder_sdk APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)

if (WIN32)
   set(LIB_EXTENSION ".lib")
else ()
   set(LIB_EXTENSION ".a")
endif ()

set_target_properties(scala_decoder::scala_decoder_sdk PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/scala_decoder_sdk${LIB_EXTENSION}"
  )

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
