'use strict';
const map=L.map('map');
L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
const groups={drivable:L.layerGroup().addTo(map),contextual:L.layerGroup().addTo(map),junctions:L.layerGroup().addTo(map),nearestJunction:L.layerGroup().addTo(map),raw:L.layerGroup().addTo(map),matched:L.layerGroup().addTo(map),gnss:L.layerGroup().addTo(map),match:L.layerGroup().addTo(map),error:L.layerGroup().addTo(map),highlight:L.layerGroup().addTo(map)};
L.control.layers(null,{'Drivable OSM highways':groups.drivable,'Contextual OSM highways':groups.contextual,'Junctions':groups.junctions,'Raw GNSS trajectory':groups.raw,'Matched-road trajectory':groups.matched,'Latest raw GNSS position':groups.gnss,'Latest matched road point':groups.match,'GNSS-to-road error':groups.error,'Currently matched OSM way':groups.highlight},{collapsed:false}).addTo(map);
const wayLookup=new Map(),junctionLookup=new Map();let initialized=false,polling=false,currentHighlight=null;
const val=v=>v===null||v===undefined||v===''?'-':String(v);
function fields(id,items){document.getElementById(id).innerHTML=items.map(([k,v])=>`<dt>${k}</dt><dd>${val(v)}</dd>`).join('')}
function roadStyle(group){return group==='drivable'?{color:'#145da0',weight:4,opacity:.72}:{color:'#795548',weight:2,opacity:.58,dashArray:'7 6'}}
async function loadRoads(){const response=await fetch('osm_highways.geojson');const data=await response.json();data.features.forEach(feature=>{const layer=L.geoJSON(feature,{style:roadStyle(feature.properties.road_group)});layer.bindPopup(Object.entries(feature.properties).map(([k,v])=>`<b>${k}</b>: ${val(v)}`).join('<br>'));layer.addTo(groups[feature.properties.road_group]);wayLookup.set(String(feature.properties.way_id),feature)});if(data.features.length){map.fitBounds(L.geoJSON(data).getBounds());initialized=true}else document.getElementById('empty').textContent='No OSM highway geometry is available.'}
function junctionText(type,count){return {T_JUNCTION:'T',Y_JUNCTION:'Y',CROSS_INTERSECTION:'+',THREE_WAY_UNKNOWN:'3?',FOUR_WAY_UNKNOWN:'4?'}[type]||val(count)}
async function loadJunctions(){const response=await fetch('junctions.geojson');const data=await response.json();(data.features||[]).forEach(feature=>{const p=feature.properties||{},coordinates=(feature.geometry||{}).coordinates||[];if(coordinates.length<2)return;junctionLookup.set(String(p.node_id),feature);const marker=L.marker([coordinates[1],coordinates[0]],{icon:L.divIcon({className:`junction-marker junction-${String(p.junction_type||'unknown').toLowerCase()}`,html:junctionText(p.junction_type,p.physical_branch_count),iconSize:[26,26],iconAnchor:[13,13]})});marker.bindPopup(`<b>${val(p.junction_type)}</b><br>node ID: ${val(p.node_id)}<br>physical branches: ${val(p.physical_branch_count)}<br>bearings: ${val((p.physical_branch_bearings_deg||[]).join(', '))}<br>way IDs: ${val((p.connected_way_ids||[]).join(', '))}<br>traffic signals: ${val(p.has_traffic_signals)}`);marker.addTo(groups.junctions)})}
function update(state){const g=state.latest_gnss,m=state.latest_match||{matched:false},j=state.nearest_junction;groups.raw.clearLayers();groups.matched.clearLayers();groups.gnss.clearLayers();groups.match.clearLayers();groups.error.clearLayers();groups.highlight.clearLayers();groups.nearestJunction.clearLayers();
if(state.gnss_track.length>1)L.polyline(state.gnss_track.map(p=>[p.latitude,p.longitude]),{color:'#d32f2f',weight:4,dashArray:'3 7'}).addTo(groups.raw);
if(state.matched_track.length>1)L.polyline(state.matched_track.map(p=>[p.latitude,p.longitude]),{color:'#6a1b9a',weight:6,opacity:.8}).addTo(groups.matched);
if(g){const pos=[g.latitude,g.longitude];L.marker(pos,{icon:L.divIcon({className:'latest-gnss',iconSize:[16,16]})}).addTo(groups.gnss);if(!initialized){map.setView(pos,17);initialized=true}if(document.getElementById('follow').checked&&!map.getBounds().pad(-.12).contains(pos))map.panTo(pos)}
if(g&&m.matched){const nearest=[m.nearest_latitude,m.nearest_longitude];L.marker(nearest,{icon:L.divIcon({className:'latest-match',iconSize:[14,14]})}).bindPopup(`distance_m: ${val(m.distance_m)}`).addTo(groups.match);L.polyline([[g.latitude,g.longitude],nearest],{color:'#111',weight:3,dashArray:'2 5'}).addTo(groups.error);const feature=wayLookup.get(String(m.way_id));if(feature)L.geoJSON(feature,{style:{color:'#ff8f00',weight:9,opacity:.95}}).addTo(groups.highlight)}
if(j){const feature=junctionLookup.get(String(j.node_id)),coordinates=feature&&feature.geometry.coordinates,p=feature&&feature.properties;if(coordinates)L.marker([coordinates[1],coordinates[0]],{icon:L.divIcon({className:'nearest-junction-marker',html:junctionText(j.junction_type,p.physical_branch_count),iconSize:[32,32],iconAnchor:[16,16]})}).bindPopup(`<b>${val(j.junction_type)}</b><br>node ID: ${val(j.node_id)}<br>distance_m: ${val(j.distance_m)}`).addTo(groups.nearestJunction)}
fields('gnss',[['timestamp',g&&g.timestamp_ns],['latitude',g&&g.latitude],['longitude',g&&g.longitude],['altitude',g&&g.altitude],['fix status',g&&g.status]]);fields('match',[['state',m.matched?'matched':'unmatched'],['way_id',m.way_id],['highway',m.highway],['name',m.name],['ref',m.ref],['maxspeed_raw',m.maxspeed_raw],['maxspeed_kmh',m.maxspeed_kmh],['lanes_raw',m.lanes_raw],['oneway_raw',m.oneway_raw],['distance_m',m.distance_m],['nearest latitude',m.nearest_latitude],['nearest longitude',m.nearest_longitude]]);fields('junction',[['Node ID',j&&j.node_id],['Type',j&&j.junction_type],['Distance',j&&`${j.distance_m.toFixed(1)} m`]]);fields('stats',[['GNSS received',state.gnss_received_count],['match attempts',state.match_attempt_count],['matched',state.matched_count],['unmatched',state.unmatched_count]]);document.getElementById('empty').textContent=!g&&!wayLookup.size?'No GNSS or OSM data is available.':''}
async function poll(){if(polling)return;polling=true;try{const r=await fetch(`runtime_state.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(r.status);const state=await r.json();const follow=document.getElementById('follow');if(!follow.dataset.ready){follow.checked=!!state.follow_vehicle_default;follow.dataset.ready='1'}update(state);const c=document.getElementById('connection');c.textContent='Live data connected';c.className=''}catch(e){const c=document.getElementById('connection');c.textContent='Disconnected / stale data — retrying';c.className='stale'}finally{polling=false}}
Promise.all([loadRoads(),loadJunctions()]).catch(()=>{document.getElementById('empty').textContent='Static map data could not be loaded.'}).finally(()=>{poll();setInterval(poll,500)});
